#!/usr/bin/env bash
# migrate-gpu-pinning.sh — move deployed llama.cpp quadlets off CDI device pinning.
#
# WHY: `AddDevice=nvidia.com/gpu=GPU-<uuid>` pins a container through the CDI spec,
# which records a /dev/nvidiaN *device node*. Minor numbers are assigned when the
# driver loads and can differ from one boot to the next, while CDI is read at
# container start — so after a reboot a stale /etc/cdi/nvidia.yaml hands the
# container the WRONG physical GPU. Fingerprint: the unit is `active`, the container
# is `Up`, /health returns ok, but a model load dies with a CUDA out-of-memory error
# for a size that comfortably fits the card the container believes it has.
#
# The durable form pins the card at the CUDA layer instead:
#     AddDevice=nvidia.com/gpu=all
#     Environment=CUDA_VISIBLE_DEVICES=GPU-<uuid>
# Every node is present, and the CUDA runtime resolves the UUID itself, so a minor
# reshuffle cannot misroute the service. Templates under scripts/templates/ ship
# this form; this script converts quadlets generated by older versions.
#
# Usage:
#   ./scripts/migrate-gpu-pinning.sh                 # dry run (default)
#   ./scripts/migrate-gpu-pinning.sh --apply         # write changes
#   ./scripts/migrate-gpu-pinning.sh --apply --quadlet-dir /path/to/quadlets
#
# Idempotent: quadlets already using gpu=all are reported and left alone.

set -euo pipefail

QUADLET_DIR="${HOME}/.config/containers/systemd"
APPLY=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --apply)       APPLY=1; shift ;;
        --quadlet-dir) QUADLET_DIR="${2:?--quadlet-dir needs a path}"; shift 2 ;;
        -h|--help)     sed -n '2,26p' "$0"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

[[ -d $QUADLET_DIR ]] || { echo "no such directory: $QUADLET_DIR" >&2; exit 1; }

say() { printf '%s\n' "$*"; }

changed=0
already=0

for f in "$QUADLET_DIR"/*.container; do
    [[ -e $f ]] || continue
    name=$(basename "$f")

    # Only touch files that still carry a UUID-pinned CDI device line.
    uuid=$(sed -n 's|^AddDevice=nvidia\.com/gpu=\(GPU-[0-9a-f-]*\)[[:space:]]*$|\1|p' "$f")
    if [[ -z $uuid ]]; then
        if grep -q '^AddDevice=nvidia.com/gpu=all' "$f"; then
            say "  unchanged  $name (already gpu=all)"
            already=$((already + 1))
        fi
        continue
    fi

    if [[ $APPLY -eq 1 ]]; then verb=rewriting; else verb="would rewrite"; fi
    say "  $verb $name -> gpu=all + CUDA_VISIBLE_DEVICES=$uuid"
    if [[ $APPLY -eq 1 ]]; then
        cp -n "$f" "$f.pre-gpu-pinning.bak"
        sed -i "s|^AddDevice=nvidia\.com/gpu=GPU-.*$|AddDevice=nvidia.com/gpu=all\nEnvironment=CUDA_VISIBLE_DEVICES=$uuid|" "$f"
    fi
    changed=$((changed + 1))
done

say ""
if [[ $changed -eq 0 ]]; then
    say "nothing to migrate in $QUADLET_DIR"
    exit 0
fi

if [[ $APPLY -eq 0 ]]; then
    say "DRY RUN — $changed quadlet(s) need migrating. Re-run with --apply to write."
    exit 0
fi

# Verify the result rather than trusting sed.
say "verifying..."
fail=0
for f in "$QUADLET_DIR"/*.container; do
    [[ -e $f ]] || continue
    grep -q '^AddDevice=nvidia.com/gpu=GPU-' "$f" && { say "  FAIL $(basename "$f") still has a CDI UUID pin"; fail=1; }
    if grep -q '^Environment=CUDA_VISIBLE_DEVICES=' "$f"; then
        say "  ok   $(basename "$f"): $(grep '^Environment=CUDA_VISIBLE_DEVICES=' "$f")"
    fi
done
[[ $fail -eq 0 ]] || exit 1

say ""
say "migrated $changed quadlet(s); backups: *.pre-gpu-pinning.bak"
say "Now reload and restart so containers are recreated:"
say "  systemctl --user daemon-reload"
say "  systemctl --user restart llama-cpp-main llama-cpp-research"
say ""
say "Verify each service sees its intended card (not both):"
say "  podman exec systemd-llama-cpp-main /app/llama-server --list-devices"
