apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://systemd-prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
  - name: VictoriaLogs
    uid: victorialogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://systemd-victorialogs:9428
